### ISSUE TITLE
Dense custom output generation in single file

### ISSUE THREAD

**Issue by adlzanchetta** [Iowa-Flood-Center/asynch#18]
Provide an option in the global file for the generation of sequential snapshots similar to the option 4, but instead of creating multiple files with a full snapshot of the system in each, it would create a single hf5 file with only some given set of parameters provided.
Usually it is needed only data of discharge (or discharge and base discharge) for forecasts. So when running forecasts for 10 days, instead of generating 240 hdf5 files of full snapshots (around 6 GB), it would generate a single hdf5 only with the discharge of all links, ignoring other states (the single file would probably have a little bit less than 1GB).

Suggestion of global file line structure:
5 TIME_INTERVAL FILE_PATH NUMBER_OF_STATES [LIST_OF_STATES_AND_LABEL]
in which:
- 5 : code of the output type
- TIME_INTERVAL: time interval in data generation (in minutes), like option 4
- FILE_PATH: where the output file will be saved
- NUMBER_OF_STATES: e.g. if I save only discharge, it is 1. If dischage+base discharge: 2
- LIST_OF_STATES_AND_LABEL: sequence of number and string (number is the index of state, string is its label). E.g.: 1 q 2 bq

Suggestion of the new h5 file structure
- index (table with link_ids)
- meta_info (table with the relationship column-label )
+ timestamps (folder)
--- 14528740 (table with the 'partial snapshot' of time  14528740)
--- 14528800 (table with the 'partial snapshot' of ...)
--- 14528860 (...)
--- ...

**Comment by sdebionne** [comment]
I believe what you are asking for is "outputs in HDF5 format". Snapshots are by definition with all state variables since there are a meant to be used as initial conditions.

Outputs are more flexible, e.g. you can choose to output discharges only at a given time step.

**Comment by sdebionne** [comment]
Added in v1.2.0
