### ISSUE TITLE
Last state = first state in sequential snapshots output

### ISSUE THREAD

**Issue by adlzanchetta** [Iowa-Flood-Center/asynch#20]
When executing a global file with option 4 for snapshots (sequential outputs equally separated in time), the states of the first snapshot created will present the same values as the last one, usually creating discontinuity in the beginning of the timeseries.

Example: 
  executing a global file with 
    snapshot option given by "4 60 /outputfolder/snapshot_00000.h5"
    rainfall forcing from **1473570000** to **1475298000**
  the value for discharge in the output files are:
    **512.687860086** -> /outputfolder/snapshot_1473570000.h5
    0.01349235402 -> /outputfolder/snapshot_1473573600.h5
    0.0212552003009 -> /outputfolder/snapshot_1473577200.h5
    0.0308037751273 -> /outputfolder/snapshot_1473580800.h5
    ...
    523.689703225 -> /outputfolder/snapshot_1475290800.h5
    518.768935853 -> /outputfolder/snapshot_1475294400.h5
    **512.687860086** -> /outputfolder/snapshot_1475298000.h5

Happened on **Neon**, running **/Dedicated/IFC/.neon/bin/asynch-1.0.1**

**Comment by sdebionne** [comment]
Fixed in v1.2.0
