### ISSUE TITLE
Config file to use?

### ISSUE THREAD

**Issue by gregjewi** [Iowa-Flood-Center/asynch#54]
I'm trying to build HLM on a linux machine. I was following the directions from the read the docs installation page, but I'm running into some trouble. Here are the commands outlined in the readthedocs:

```mkdir build && cd build
../configure CFLAGS="-O3 -DNDEBUG"
make
make check
make install
```

First, there isn't a file called config. But, there's a `configure.ac` in the root dir. I tried using that, but my permission was denied. I then made the file executable through `chmod +x configure.ac` and tried again. I get this error:

```
../configure.ac: line 1: syntax error near unexpected token `[asynch],'
../configure.ac: line 1: `AC_INIT([asynch], [1.4.3], [andre-zanchetta@uiowa.edu])'
```

Is there a different config file somebody can give me? Advice on how to update this one? Any help is appreciated.

**Comment by sdebionne** [comment]
`configure.ac` is the source of the `configure` script. It needs to be generated using `autoconf`. I think our tarballs used to provide a prebuilt  `./configure` but if you got the code directly from the repo, then you need to [run autoconf manually](https://www.gnu.org/software/autoconf/manual/autoconf-2.61/html_node/Making-configure-Scripts.html).

**Comment by gregjewi** [comment]
Thanks. I ran autoconf etc to build configure file. I'm now getting an error(s) on build. Looking through the `config.log` the first errors I get are "fatal errors" when checking the gcc (and mpicc) versions. See below:

```
...
configure:3342: mpicc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3353: $? = 4
configure:3342: mpicc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
...
configure:4791: mpicc -std=gnu99 -E  conftest.c
conftest.c:12:28: fatal error: ac_nonexistent.h: No such file or directory
 #include <ac_nonexistent.h>
                            ^
compilation terminated.
configure:4791: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "asynch"
| #define PACKAGE_TARNAME "asynch"
| #define PACKAGE_VERSION "1.4.3"
| #define PACKAGE_STRING "asynch 1.4.3"
| #define PACKAGE_BUGREPORT "andre-zanchetta@uiowa.edu"
| #define PACKAGE_URL ""
| #define PACKAGE "asynch"
| #define VERSION "1.4.3"
| #define HAVE_MPI 1
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:4816: result: mpicc -std=gnu99 -E
configure:4836: mpicc -std=gnu99 -E  conftest.c
configure:4836: $? = 0
configure:4850: mpicc -std=gnu99 -E  conftest.c
conftest.c:12:28: fatal error: ac_nonexistent.h: No such file or directory
 #include <ac_nonexistent.h>
                            ^
compilation terminated.
...
configure:5949: gfortran -V >&5
gfortran: error: unrecognized command line option '-V'
gfortran: fatal error: no input files
compilation terminated.
configure:5960: $? = 4
configure:5949: gfortran -qversion >&5
gfortran: error: unrecognized command line option '-qversion'
gfortran: fatal error: no input files
compilation terminated.
...
```
I do not understand why these are fatal errors if the gcc version was returned with a previous command `mpicc -v` for example. Are these fatal errors like it says? Or would there be something else in later in the config log that I should be looking at? (I get others in the 1500+ lines of `config.log`... wouldn't share the whole thing here.)

thanks
G

**Comment by gregjewi** [comment]
OK... I finally got things compiled. The [last] error I fixed was compiling with/without zlib. The error handler said I could add a flag `--without-zlib` but when I did that the compiler was getting hung up in `compression.o`. After adding zlib it compiled fine. 

thanks for the help.
