### ISSUE TITLE
Which RK Methods work?

### ISSUE THREAD

**Issue by gregjewi** [Iowa-Flood-Center/asynch#55]
Hoping to get some feedback on which methods, in general, are actually trustworthy. 

For a refresher [here are the options](https://asynch.readthedocs.io/en/latest/builtin_options.html#rk-methods):

![image](https://user-images.githubusercontent.com/14804791/102812980-a6a1bf80-438d-11eb-9d34-af7026e45228.png)

The default method is # 2, the Dormand and Prince method. I've tried running the test example with all of the explicit methods listed here. The Radaull doesn't simulate (fatal error,) while the other three explicit methods produce these results:

![image](https://user-images.githubusercontent.com/14804791/102813680-d8675600-438e-11eb-89d0-ec6f239be992.png)

Even with the most simple example, only method # 2 returns a result that is plausible. Does anyone have an explanation? Should I only use Dormand and Prince? If The RK Method (# 1) were to be working it *should* provide better results than Kutta and worse results than D&P.

**Comment by gregjewi** [comment]
Update: similar behavior with the other example network Clear Creek.

![image](https://user-images.githubusercontent.com/14804791/102829840-926dba80-43ad-11eb-8192-84369b9e29a5.png)

Suggests The RK method isn't functional.

**Comment by sdebionne** [comment]
AFAIR, the only method that has a dense output steppers is dopri5 aka Dormand and Prince. Dense output steppers can interpolate the solution to calculate the state x(t') at any point t <= t' <= t+dt. Asynch uses these interpolations internally -this is actually where the name asynch come from. I would consider the other integrators as references but not to be used for actual computation, at least for the IFC use cases.

**Comment by gregjewi** [comment]
Thanks for explanation.
