### ISSUE TITLE
Creating a container for asynch in Singularity / Docker

### ISSUE THREAD

**Issue by fquintero82** [Iowa-Flood-Center/asynch#60]
Hello all,

I would like your opinion on a project i would like to start working.
I think we all know how difficult can be compiling and successfully running asynch in a machine different to the UIOWA HPC environment. 

Sam and Andre left instructions on how to properly create a executable binary with static linkage that includes the dependency libraries, but often this stills leads to problems, most likely with hdf and openmpi libraries.

Also, there has been interest from external researchers for running asynch in their computers, and that can include windows machines.

I would like to propose creating a minimal container (e.g. docker, singularity) that includes all the environment required to run asynch. This would provide asynch with a great portability / mobility. I mentioned docker just to provide some context, but my understanding is that docker is not a feasible solution for HPC. Instead, singularity seems to provide a better solution. Here is some explanation on the topic https://wiki.uiowa.edu/display/hpcdocs/Singularity+Containers

This is new territory for me. If any of you have previous experience with containers and ideas on how to implement it for asynch, i would like to hear your comments. 

Also, i don't know who is reading this post. Is there any way to distribute it to all the contributors of the project ? (Sam, Scott, Andre, Nico, Greg)

Thanks,

**Comment by sdebionne** [comment]
Hola Felipe,
Nice to hear from you! And to read that the project is alive and is even gaining momentum with users outside the IFC.

If I understand correctly what you mean with "how difficult can be compiling and successfully running", you are  facing a packaging and dependency management issue.

I would suggest looking at [Conda](https://docs.conda.io/en/latest/), a package manager that could fit your needs and already has plenty of scientific computing packages. I have some experience with Conda and could help you write a recipe. Let me know if you are interested.

Once a package for asynch is been build, the installation, anywhere, including the HPC infra of the UoI, would be as simple as

```
conda install asynch
```

This would get all the dependencies (MPI, netcfd, hdf5 , you name it) as well and install it in an environment independent of the system. The benefits is that you could easily have multiple versions of asynch installed (in different env).

There is no virtualization involved, it's very lightweight, much like the `venv` of Python.

HTH, Cheers!

**Comment by fquintero82** [comment]
Hi Sam,

Thanks a lot for replying. 
I didn't know that conda also could manage environments. That is awesome, and definitely a simpler and better solution for this problem. We are definitely interested in a 'recipe' , and we can start building from there. I am also interested in your recipe of profiteroles, but that is for another day :)

Felipe

**Comment by sdebionne** [comment]
For profiteroles, I would recommend the [Chocolatey package manager](https://chocolatey.org/), it's definitely yummy!

**Comment by fquintero82** [comment]
Hello,

I have been working on a conda-build recipe for asynch.
I created a conda environment containing all the dependency libraries. I also included openmpi and the gcc compiler. I am trying first using the versions of the libraries that we know work because are the ones used in Argon.

conda create --name b1
conda activate b1
conda install zlib=1.2.11 
conda install -c birdhouse/label/dev szip
conda install hdf5=1.8.18
conda install -c cryoem openmpi (version 2.0.1)
conda install -c anaconda libpq=12.2 (older versions 9.5 gave me problems)
conda install gxx_linux-64=5.4.0

I added a PREFIX env variable and added it to the ./configure to build asynch using the libraries in the environment
export PREFIX="${CONDA_PREFIX}"
export CONDA_BUILD="1"
autoreconf --install
mkdir build
cd build
make clean
../configure CFLAGS="-O3 -DNDEBUG -Wno-format-security" --prefix=${CONDA_PREFIX}
make

The compilation runs without problems, and creates a binary linked dynamically.
When i run one of the examples , this particular machine (the sandbox 65 server) has a different version of libhdf5 (version 1.8.5) and will crash. But ok, thats why we are doing this conda package, to create a binary that doesn't depend on the system libraries.

I went and compiled asynch using static linking as follows

mpicc -std=gnu99 -O3 -march=core-avx2 -DNDEBUG \
-I"${PREFIX}"/include \
-I/usr/include \
-L"${PREFIX}"/lib \
-L/usr/lib64 -L/usr/lib -L/usr/lib \
-o src/asynch src/optparse.o src/asynch_cli.o src/libasynch.a \
"${PREFIX}"/lib/libhdf5_hl.a \
"${PREFIX}"/lib/libhdf5.a \
"${PREFIX}"/lib/libz.a \
"${PREFIX}"/lib/libsz.a \
"${PREFIX}"/lib/libpq.a -lm -ldl

but then i got a lot of errors of 'undefined reference'. 

I have two basic questions:
1) is part of the goal of building the conda package,  being able to build a static linked version of asynch using the libraries of the environment?

2) I don't got errors in the dynamic linking compilation, but got errors in the static linking. Does that mean that there is a compatibility issue with the version of the libraries I am using?

3) Is there a way to force asynch to run using the conda environment, without looking at other libraries? I have read that is a bad idea changing the LD_LIBRARY_PATH to the conda environment, but i dont know if its part of the trick.

Any thoughts are welcome.
Felipe

**Comment by sdebionne** [comment]
> I have two basic questions:

I see three questions but nevermind :-)

1. The Conda package can include static or shared or both libraries, the python binding, the async executable, it's really up to you!
2. It's hard to tell, some libraries require a macro to be defined when building with the  static version of the library. Might be the case of HDF5.
3. Once you have a working recipe and consequently a conda package, you will not need to mess up with `LD_LIBRARY_PATH` anymore. `conda install asynch` will install everything you need in the environment.

I started working on a recipe, see #61. It's not working yet, the build system needs to be adapted. To be more specific, MPI is not found by the `configure` script but I am not sure why.

To build the package, you need to `conda install conda-build`and then run `conda build <path to asynch>/conda` where `conda` is a subfolder containing the recipe.

**Comment by gregjewi** [comment]
Would one need to change the asynch source code to be able to change the DLLs dependencies to statically linked? How I understand the difference, an exe looks for statically linked on build and looks for dynamically linked on run. Doesn't that suggest we'd need to change how asynch references an outside library in order to "convert" dll behavior to a static compilation?

One of the places where I looked for info: https://stackoverflow.com/a/311889

PS. this is a question more than an answer.

**Comment by sdebionne** [comment]
@gregjewi You can build  `asynch` against static or shared libraries, it's really a matter of making the executable standalone or not -standalone being easier to deploy. But since package managers such as Conda solve most of the issues, I see no reason to use static libraries here. Does that answer you question?

**Comment by tdnavarrom** [comment]
Just finished it 👍
